
TARGET = 'pixelize'
SOURCES = ['Pixelize.cpp', '../common/Surface.cpp']
LIBS = []
FRAMEWORKS = []
ECCFLAGS = ''

DEBUG = 1

SConscript('../common/SConscript',
	exports = ['DEBUG', 'SOURCES', 'TARGET', 'LIBS', 'FRAMEWORKS', 'ECCFLAGS'])

