
TARGET = 'dither'
SOURCES = ['Dither.cpp']
LIBS = []
FRAMEWORKS = []
ECCFLAGS = ''

DEBUG = 1

SConscript('../common/SConscript',
	exports = ['DEBUG', 'SOURCES', 'TARGET', 'LIBS', 'FRAMEWORKS', 'ECCFLAGS'])

